version: "3"
services:
  db:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data

  wait_for_db:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
    command: db:5432

  tomcat8:
    depends_on:
      - wait_for_db
    image: tomcat:alpine
    volumes:
      - ./webapps:/usr/local/tomcat/webapps

  nginx:
    image: nginx:1.15-alpine
    depends_on:
      - tomcat8
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80